//
//  DeveloperPreview.swift
//  ProjetoSwiftUI
//
//  Created by Vitor Campos on 07/11/23.
//

import SwiftUI

struct DeveloperPreview {
    var listings: [Listing] = [
        .init(id: NSUUID().uuidString,
              owneUid: NSUUID().uuidString,
              ownerName: "Alice Johnson",
              ownerImageUrl: "female-profile",
              numberOfBedrooms: 3,
              numbersOfBethrooms: 2,
              numbersOfguests: 2,
              numbersOfBeds: 2, 
              numberOfNights: 5,
              pricePerNight: 450,
              latitude: 34.0522,
              longitude: -118.2437,
              imageURLs: ["listing-7", "listing-8", "listing-9", "listing-10"],
              address: "567 Oak St",
              city: "Los Angeles",
              state: "California",
              title: "Cozy Bungalow",
              rating: 4.75,
              features: [.selfCheckIn],
              amenities: [.wifi, .kitchen],
              type: .apartment),
        .init(id: NSUUID().uuidString,
              owneUid: NSUUID().uuidString,
              ownerName: "Michael Davis",
              ownerImageUrl: "male-profile",
              numberOfBedrooms: 2,
              numbersOfBethrooms: 1,
              numbersOfguests: 3,
              numbersOfBeds: 2, 
              numberOfNights: 2,
              pricePerNight: 300,
              latitude: 40.7128,
              longitude: -74.0060,
              imageURLs: ["listing-3", "listing-4", "listing-5", "listing-6"],
              address: "789 Pine St",
              city: "New York",
              state: "New York",
              title: "Downtown Apartment",
              rating: 4.92,
              features: [.superHost],
              amenities: [.wifi, .tv],
              type: .apartment),
        .init(id: NSUUID().uuidString,
              owneUid: NSUUID().uuidString,
              ownerName: "Daniel Martinez",
              ownerImageUrl: "male-profile",
              numberOfBedrooms: 1,
              numbersOfBethrooms: 1,
              numbersOfguests: 2,
              numbersOfBeds: 1,
              numberOfNights: 10,
              pricePerNight: 150,
              latitude: 37.7749,
              longitude: -122.4194,
              imageURLs:  ["listing-1", "listing-2", "listing-3", "listing-4"],
              address: "456 Elm St",
              city: "San Francisco",
              state: "California",
              title: "Cozy Studio",
              rating: 4.65,
              features: [.selfCheckIn],
              amenities: [.wifi, .kitchen, .tv, .office],
              type: .villa),
        .init(
            id: NSUUID().uuidString,
            owneUid: NSUUID().uuidString,
            ownerName: "Sophia Brown",
            ownerImageUrl: "female-profile",
            numberOfBedrooms: 3,
            numbersOfBethrooms: 2,
            numbersOfguests: 4,
            numbersOfBeds: 3, 
            numberOfNights: 6,
            pricePerNight: 500,
            latitude: 37.7749,
            longitude: -122.4194,
            imageURLs:  ["listing-5", "listing-6", "listing-7", "listing-8"],
            address: "789 Oak St",
            city: "San Francisco",
            state: "California",
            title: "Modern Apartment",
            rating: 4.95,
            features: [.selfCheckIn, .superHost],
            amenities: [.wifi, .laundry, .tv, .kitchen],
            type: .apartment),
        .init(id: NSUUID().uuidString,
              owneUid: NSUUID().uuidString,
              ownerName: "Ethan Taylor",
              ownerImageUrl: "male-profile",
              numberOfBedrooms: 4,
              numbersOfBethrooms: 3,
              numbersOfguests: 6,
              numbersOfBeds: 4, 
              numberOfNights: 1,
              pricePerNight: 600,
              latitude: 33.6844,
              longitude: -117.8265,
              imageURLs: ["listing-9", "listing-10", "listing-1", "listing-2"],
              address: "456 Pine St",
              city: "Orange County",
              state: "California",
              title: "Spacious Townhouse",
              rating: 4.75,
              features: [.superHost],
              amenities: [.wifi, .laundry, .tv, .balcony],
              type: .townHouse)
    ]
}
